### ISSUE TITLE
Volunteer to create Windows releases for you

### ISSUE THREAD

**Issue by Gitoffthelawn** [Fushko/gammy#82]
@Fushko I recall you mentioning somewhere that it is currently time-consuming for you to create Windows executable releases.

I'm happy to volunteer to do that for you if the releases can be created with portable & free software.  If the build requirements are portable and free, I can do it right away.

**Comment by Fushko** [comment]
> I recall you mentioning somewhere that it is currently time-consuming for you to create Windows executable releases.

It's not anymore :) The last release has been skipped simply because the changes were virtually all linux related.
Besides, I would have to provide build instructions for windows (#15), but right now I don't know a way to build that doesn't involve downloading the Qt installer (which requires an account again, ugh) and the Qt Creator IDE along with it.
